<!--
  Transforms (PRD-002 v1.3, 2026-05-31)
  ─────────────────────────────────────
  Atomic CRUD for the Velero ResourceModifier rule bundle layer. The visual
  rule editor that lived in TransformSets.vue (single-layer v0.8.x model)
  moved here; TransformSets is now a pure CONTAINER that references
  Transforms by name (see TransformSets.vue).

  Page layout — same shape as the old TransformSets page so the muscle
  memory carries over:
    - Page header (title + Create button)
    - Filter row (search by name / description)
    - Card grid: name + description + rule count + builtin / auto badges
    - Drawer for create / edit / view (clone-to-edit for built-ins)
    - Inline YAML preview at the bottom for power users

  Pre-flight "Apply Suggested Fix" lands here via
    /transforms?name=<auto-generated-transform-name>
  so the user can review the auto-generated rules before wiring it into a
  Transform Set. The query also accepts ?fromConflict=&payload= from the
  RestoreDrawer "Go to Transform" CTA — pre-fills the editor with a fresh
  rule shaped to the conflict.
-->
<template>
  <div class="ts-page">
    <div class="page-header">
      <div>
        <h3>{{ t('transforms.title') }}</h3>
        <p class="page-desc">{{ t('transforms.desc') }}</p>
      </div>
      <el-button type="primary"
        :disabled="!auth.canDo('transformset.crud')"
        :title="!auth.canDo('transformset.crud') ? t('common.noPermission') : ''"
        @click="openEditor(null)">
        <el-icon><Plus /></el-icon> {{ t('transforms.create') }}
      </el-button>
    </div>

    <div v-if="fromConflictKind" class="from-conflict-banner">
      <el-icon><InfoFilled /></el-icon>
      <div>
        <div class="fc-title">{{ t('transforms.fromConflictTitle', { kind: fromConflictKind }) }}</div>
        <div class="fc-hint">{{ t('transforms.fromConflictHint') }}</div>
      </div>
    </div>

    <div class="filter-toolbar">
      <el-input
        v-model="filter"
        :placeholder="t('transforms.filterPlaceholder')"
        clearable
        class="filter-input"
      >
        <template #prefix><el-icon><Search /></el-icon></template>
      </el-input>
      <span class="spacer"></span>
      <span class="result-count">{{ t('transforms.count', { n: filtered.length, total: items.length }) }}</span>
    </div>

    <div v-if="loading && items.length === 0" class="loading">
      <el-icon class="rot"><Loading /></el-icon> {{ t('common.loading') }}
    </div>
    <div v-else-if="filtered.length === 0" class="empty">
      <el-icon><InfoFilled /></el-icon>
      <div>{{ t('transforms.empty') }}</div>
    </div>
    <div v-else class="ts-grid">
      <div v-for="tr in filtered" :key="tr.name" class="ts-card" :class="{ 'is-highlighted': tr.name === highlightName }">
        <div class="ts-card-head">
          <div class="ts-name">
            <el-icon><Tools /></el-icon>
            <span>{{ tr.name }}</span>
            <span v-if="tr.builtIn" class="builtin-pill">{{ t('transforms.builtin') }}</span>
            <span v-if="isAutoGenerated(tr)" class="auto-pill" :title="t('transforms.autoGeneratedHint')">{{ t('transforms.autoGenerated') }}</span>
          </div>
          <el-dropdown trigger="click" @command="cmd => handleCommand(cmd, tr)">
            <button class="more-btn" type="button"><span class="dots">⋮</span></button>
            <template #dropdown>
              <el-dropdown-menu>
                <el-dropdown-item command="view">{{ t('common.view') }}</el-dropdown-item>
                <el-dropdown-item command="edit" :disabled="tr.builtIn">{{ t('common.edit') }}</el-dropdown-item>
                <el-dropdown-item command="clone">{{ t('transforms.clone') }}</el-dropdown-item>
                <el-dropdown-item command="delete" divided :disabled="tr.builtIn">{{ t('common.delete') }}</el-dropdown-item>
              </el-dropdown-menu>
            </template>
          </el-dropdown>
        </div>
        <div class="ts-desc">{{ tr.description || t('transforms.noDesc') }}</div>
        <div class="ts-meta">
          <span class="meta-chip">{{ t('transforms.ruleCount', { n: (tr.rules || []).length }) }}</span>
          <span class="meta-chip">{{ totalPatchCount(tr) }} {{ t('transforms.patches') }}</span>
        </div>
        <div class="ts-rules-preview">
          <div v-for="(rule, ri) in (tr.rules || []).slice(0, 2)" :key="ri" class="rule-mini">
            <span class="rule-gr">{{ rule.conditions.groupResource }}</span>
            <span class="rule-arrow">→</span>
            <span v-for="(p, pi) in rule.patches" :key="pi" class="rule-op">
              {{ p.operation }} <code>{{ p.path }}</code>
            </span>
          </div>
          <div v-if="(tr.rules || []).length > 2" class="rule-more">+{{ tr.rules.length - 2 }} more rule(s)</div>
        </div>
      </div>
    </div>

    <!-- Editor / Viewer drawer -->
    <el-drawer
      v-model="drawerOpen"
      :title="editorTitle"
      direction="rtl"
      size="640px"
      :close-on-click-modal="false"
    >
      <div v-if="form" class="editor-body">
        <el-form :model="form" label-position="top">
          <el-form-item :label="t('common.name')" required>
            <el-input v-model="form.name" :disabled="!!editingName" placeholder="my-transform" />
          </el-form-item>
          <el-form-item :label="t('transforms.description')">
            <el-input v-model="form.description" type="textarea" :rows="2"
              :placeholder="t('transforms.descriptionPlaceholder')" />
          </el-form-item>

          <div class="rules-section">
            <div class="rules-header">
              <span class="rules-title">{{ t('transforms.rules') }}</span>
              <el-button size="small" :disabled="readOnly" @click="addRule">
                <el-icon><Plus /></el-icon> {{ t('transforms.addRule') }}
              </el-button>
            </div>

            <div v-for="(rule, ri) in form.rules" :key="ri" class="rule-editor">
              <div class="rule-editor-head">
                <span class="rule-num">#{{ ri + 1 }}</span>
                <el-button size="small" type="danger" circle :disabled="readOnly || form.rules.length <= 1" @click="removeRule(ri)">
                  <el-icon><Close /></el-icon>
                </el-button>
              </div>

              <el-form-item :label="t('transforms.groupResource')" required>
                <el-input v-model="rule.conditions.groupResource" :disabled="readOnly"
                  placeholder="services, deployments.apps, persistentvolumeclaims" />
              </el-form-item>
              <el-form-item :label="t('transforms.namespaces')">
                <el-select v-model="rule.conditions.namespaces" multiple filterable allow-create
                  :disabled="readOnly"
                  :placeholder="t('transforms.allNamespaces')">
                  <el-option v-for="ns in namespaces" :key="ns" :label="ns" :value="ns" />
                </el-select>
              </el-form-item>
              <el-form-item :label="t('transforms.resourceNameRegex')">
                <el-input v-model="rule.conditions.resourceNameRegex" :disabled="readOnly"
                  :placeholder="t('transforms.resourceNameRegexHint')" />
              </el-form-item>

              <div class="patches-section">
                <div class="patches-head">
                  <span>{{ t('transforms.patches') }}</span>
                  <el-button size="small" :disabled="readOnly" @click="addPatch(rule)">
                    <el-icon><Plus /></el-icon> {{ t('transforms.addPatch') }}
                  </el-button>
                </div>
                <div v-for="(patch, pi) in rule.patches" :key="pi" class="patch-row">
                  <el-select v-model="patch.operation" class="patch-op" :disabled="readOnly">
                    <el-option v-for="op in ['add','remove','replace','test','copy','move']" :key="op" :label="op" :value="op" />
                  </el-select>
                  <el-input v-model="patch.path" :placeholder="t('transforms.pathPlaceholder')" class="patch-path" :disabled="readOnly" />
                  <el-input
                    v-if="['add','replace','test'].includes(patch.operation)"
                    v-model="patch.value"
                    :placeholder="t('transforms.valuePlaceholder')"
                    class="patch-value"
                    :disabled="readOnly"
                  />
                  <el-button size="small" type="danger" circle :disabled="readOnly || rule.patches.length <= 1" @click="removePatch(rule, pi)">
                    <el-icon><Close /></el-icon>
                  </el-button>
                </div>
              </div>
            </div>
          </div>

          <details class="yaml-preview">
            <summary>{{ t('transforms.yamlPreview') }}</summary>
            <pre>{{ yamlPreview }}</pre>
          </details>
        </el-form>
      </div>
      <template #footer>
        <el-button @click="drawerOpen = false">{{ t('common.cancel') }}</el-button>
        <el-button type="primary" :loading="saving" :disabled="readOnly" @click="handleSave">
          {{ readOnly ? t('common.close') : (editingName ? t('common.save') : t('common.create')) }}
        </el-button>
      </template>
    </el-drawer>
  </div>
</template>

<script setup>
import { ref, computed, onMounted, watch } from 'vue'
import { useI18n } from 'vue-i18n'
import { useRoute, useRouter } from 'vue-router'
import { Close, InfoFilled, Loading, Plus, Search, Tools } from '@element-plus/icons-vue'
import { ElMessage, ElMessageBox } from 'element-plus'
import {
  getTransforms, createTransform, updateTransform, deleteTransform,
  getNamespaces
} from '../api/velero'

const { t } = useI18n()
const route = useRoute()
const router = useRouter()
import { useAuth } from '../composables/useAuth'
const auth = useAuth()

const items = ref([])
const namespaces = ref([])
const loading = ref(false)
const filter = ref('')
const drawerOpen = ref(false)
const editingName = ref('')
const readOnly = ref(false)
const form = ref(null)
const saving = ref(false)

// PRD-001 v2 (#104) carryover: when RestoreDrawer's "Go to Transform" CTA
// navigates here it passes ?fromConflict=&payload= so we can pre-fill a
// fresh editor with the conflict context. Pre-flight "Apply Suggested Fix"
// passes ?name=<auto-generated-transform> instead — opens that transform
// in view-mode so the user can audit before adding to a Transform Set.
const fromConflictKind = ref('')
const fromConflictPayload = ref(null)
const highlightName = ref('')

const filtered = computed(() => {
  const q = filter.value.trim().toLowerCase()
  if (!q) return items.value
  return items.value.filter(tr => (tr.name + ' ' + (tr.description || '')).toLowerCase().includes(q))
})

const editorTitle = computed(() => {
  if (readOnly.value) return t('transforms.viewTitle', { name: editingName.value })
  if (editingName.value) return t('transforms.editTitle', { name: editingName.value })
  return t('transforms.createTitle')
})

// The backend's Transform shape doesn't carry an `autoGenerated` field —
// Pre-flight's ApplyConflictFixes labels the CM with
// supkube.io/auto-generated=true server-side, but configMapToTransform
// doesn't surface that label. The auto-generated name convention is the
// stable signal: ApplyConflictFixes prefixes every name with "preflight-fix-".
function isAutoGenerated(tr) {
  return typeof tr.name === 'string' && tr.name.startsWith('preflight-fix-')
}

function totalPatchCount(tr) {
  return (tr.rules || []).reduce((s, r) => {
    return s + (r.patches?.length || 0) + (r.mergePatches?.length || 0) + (r.strategicPatches?.length || 0)
  }, 0)
}

const yamlPreview = computed(() => {
  if (!form.value) return ''
  // Hand-rolled mini-emitter — same shape as the backend's sigs.k8s.io/yaml
  // marshaler produces for the Velero ResourceModifier doc. Power users
  // copy/paste this into a YAML linter or compare against the on-disk CM.
  const lines = ['version: v1', 'resourceModifierRules:']
  for (const rule of form.value.rules) {
    lines.push('  - conditions:')
    lines.push(`      groupResource: ${rule.conditions.groupResource || ''}`)
    if (rule.conditions.namespaces?.length) {
      lines.push('      namespaces:')
      for (const n of rule.conditions.namespaces) lines.push(`        - ${n}`)
    }
    if (rule.conditions.resourceNameRegex) {
      lines.push(`      resourceNameRegex: ${JSON.stringify(rule.conditions.resourceNameRegex)}`)
    }
    if (rule.patches?.length) {
      lines.push('    patches:')
      for (const p of rule.patches) {
        lines.push(`      - operation: ${p.operation}`)
        lines.push(`        path: ${JSON.stringify(p.path)}`)
        if (['add','replace','test'].includes(p.operation) && p.value !== undefined && p.value !== '') {
          lines.push(`        value: ${JSON.stringify(p.value)}`)
        }
      }
    }
  }
  return lines.join('\n')
})

async function fetchItems() {
  loading.value = true
  try {
    const res = await getTransforms()
    items.value = res.data.items || []
  } catch (e) {
    ElMessage.error('Failed to load Transforms: ' + (e.response?.data?.error || e.message))
  } finally {
    loading.value = false
  }
}

async function fetchNamespaces() {
  try {
    const res = await getNamespaces()
    namespaces.value = (res.data.items || []).map(ns => ns.metadata?.name || ns)
  } catch {}
}

function openEditor(tr) {
  editingName.value = tr ? tr.name : ''
  readOnly.value = !!(tr && tr.builtIn)
  form.value = tr ? deepClone(tr) : freshForm()
  drawerOpen.value = true
}

function openViewer(tr) {
  editingName.value = tr.name
  readOnly.value = true
  form.value = deepClone(tr)
  drawerOpen.value = true
}

function freshForm() {
  return {
    name: '',
    description: '',
    rules: [{
      conditions: { groupResource: '', namespaces: [], resourceNameRegex: '' },
      patches: [{ operation: 'remove', path: '', value: '' }]
    }]
  }
}

function deepClone(o) { return JSON.parse(JSON.stringify(o)) }

function addRule() {
  form.value.rules.push({
    conditions: { groupResource: '', namespaces: [], resourceNameRegex: '' },
    patches: [{ operation: 'remove', path: '', value: '' }]
  })
}
function removeRule(idx) { form.value.rules.splice(idx, 1) }
function addPatch(rule) {
  rule.patches.push({ operation: 'remove', path: '', value: '' })
}
function removePatch(rule, idx) { rule.patches.splice(idx, 1) }

async function handleSave() {
  if (readOnly.value) { drawerOpen.value = false; return }
  saving.value = true
  try {
    // Strip empty fields so the backend's strict validation accepts the
    // payload — empty strings are different from omitted keys for several
    // Velero fields (ResourceNameRegex would match nothing instead of
    // matching everything).
    const payload = deepClone(form.value)
    for (const rule of payload.rules) {
      if (!rule.conditions.namespaces?.length) delete rule.conditions.namespaces
      if (!rule.conditions.resourceNameRegex) delete rule.conditions.resourceNameRegex
      for (const p of (rule.patches || [])) {
        if (!['add','replace','test'].includes(p.operation)) delete p.value
        else if (p.value === '' || p.value === null) delete p.value
      }
    }
    if (editingName.value) {
      await updateTransform(editingName.value, payload)
      ElMessage.success(t('transforms.savedToast', { name: editingName.value }))
    } else {
      await createTransform(payload)
      ElMessage.success(t('transforms.createdToast', { name: payload.name }))
    }
    drawerOpen.value = false
    await fetchItems()
  } catch (e) {
    ElMessage.error(e.response?.data?.error || e.message)
  } finally {
    saving.value = false
  }
}

async function handleCommand(cmd, tr) {
  switch (cmd) {
    case 'view': openViewer(tr); break
    case 'edit': openEditor(tr); break
    case 'clone':
      openEditor({ ...deepClone(tr), name: tr.name + '-copy', builtIn: false })
      editingName.value = ''
      readOnly.value = false
      break
    case 'delete': await confirmDelete(tr); break
  }
}

async function confirmDelete(tr) {
  try {
    await ElMessageBox.confirm(
      t('transforms.deleteConfirm', { name: tr.name }),
      t('transforms.deleteTitle'),
      { type: 'warning', confirmButtonText: t('common.delete'), cancelButtonText: t('common.cancel') }
    )
  } catch { return }
  try {
    await deleteTransform(tr.name)
    ElMessage.success(t('transforms.deletedToast', { name: tr.name }))
    await fetchItems()
  } catch (e) {
    // The backend returns 409 with body { error, referencingTransformSets: [...] }
    // when at least one TransformSet still references this Transform. Surface
    // the list so the user knows exactly which TransformSets to edit first.
    const refs = e.response?.data?.referencingTransformSets
    if (e.response?.status === 409 && Array.isArray(refs) && refs.length > 0) {
      ElMessageBox.alert(
        t('transforms.deleteBlockedBody', { name: tr.name, n: refs.length, sets: refs.join(', ') }),
        t('transforms.deleteBlockedTitle'),
        { type: 'warning' }
      )
      return
    }
    ElMessage.error(e.response?.data?.error || e.message)
  }
}

// React to query params on mount AND every route change (the user can land
// here multiple times from different RestoreDrawer sessions without a full
// page reload).
async function applyQuery() {
  fromConflictKind.value = (route.query.fromConflict || '').toString()
  highlightName.value = ''
  if (route.query.payload) {
    try {
      const json = decodeURIComponent(escape(atob(route.query.payload.toString())))
      fromConflictPayload.value = JSON.parse(json)
    } catch (e) {
      console.warn('Failed to decode conflict payload:', e)
      fromConflictPayload.value = null
    }
  } else {
    fromConflictPayload.value = null
  }

  // Pre-flight Apply Fix: open the auto-generated Transform for review.
  if (route.query.name) {
    const name = route.query.name.toString()
    highlightName.value = name
    // Wait for items to be present so we can locate the entry.
    if (items.value.length === 0) await fetchItems()
    const found = items.value.find(tr => tr.name === name)
    if (found) {
      openViewer(found)
    } else {
      // The Transform might have just been created server-side and not yet
      // in our cached list — re-fetch once more before giving up.
      await fetchItems()
      const retry = items.value.find(tr => tr.name === name)
      if (retry) openViewer(retry)
    }
    return
  }

  // RestoreDrawer "Go to Transform" → fresh editor pre-loaded with the
  // conflict's groupResource + a starter patch. The fields below are
  // best-effort; the user finishes the editing.
  if (fromConflictPayload.value && !drawerOpen.value) {
    const f = freshForm()
    const c = fromConflictPayload.value
    const kind = c?.artifact?.kind || ''
    const group = c?.artifact?.group || ''
    let gr = ''
    if (kind) {
      gr = kind.toLowerCase() + 's'
      if (group) gr = gr + '.' + group
    }
    f.rules[0].conditions.groupResource = gr
    if (c?.artifact?.namespace) f.rules[0].conditions.namespaces = [c.artifact.namespace]
    if (c?.artifact?.name) f.rules[0].conditions.resourceNameRegex = `^${escapeRegex(c.artifact.name)}$`
    const st = c?.suggestedTransform
    if (st?.operation && st?.path) {
      f.rules[0].patches = [{ operation: st.operation, path: st.path, value: st.value ?? '' }]
    }
    form.value = f
    editingName.value = ''
    readOnly.value = false
    drawerOpen.value = true
  }
}

function escapeRegex(s) {
  return String(s).replace(/[.*+?^${}()|[\]\\]/g, '\\$&')
}

onMounted(async () => {
  await Promise.all([fetchItems(), fetchNamespaces()])
  await applyQuery()
})

watch(() => route.query, () => { applyQuery() })
</script>

<style scoped>
.ts-page { padding: 0; }
.page-header { display: flex; justify-content: space-between; align-items: flex-start; margin-bottom: 18px; }
.page-header h3 { margin: 0 0 4px 0; font-size: 20px; font-weight: 600; }
.page-desc { margin: 0; color: var(--sk-text-caption); font-size: 13px; max-width: 720px; line-height: 1.5; }

.from-conflict-banner {
  display: flex; gap: 10px; align-items: flex-start;
  background: #ecf5ff; border-left: 3px solid #409eff; border-radius: 0 6px 6px 0;
  padding: 10px 14px; margin-bottom: 14px;
}
.from-conflict-banner .el-icon { color: #409eff; margin-top: 2px; }
.fc-title { font-size: 13px; font-weight: 600; color: #1f2329; }
.fc-hint { font-size: 12.5px; color: var(--sk-text-muted); line-height: 1.5; margin-top: 2px; }

.filter-toolbar { display: flex; align-items: center; gap: 12px; margin-bottom: 14px; }
.filter-input { width: 300px; }
.spacer { flex: 1; }
.result-count { color: var(--sk-text-muted); font-size: 13px; }

.ts-grid {
  display: grid;
  grid-template-columns: repeat(auto-fill, minmax(360px, 1fr));
  gap: 14px;
}
.ts-card {
  background: #fff;
  border: 1px solid var(--sk-border);
  border-radius: 8px;
  padding: 14px 16px 12px;
  transition: box-shadow 0.15s;
}
.ts-card:hover { box-shadow: 0 2px 8px rgba(0,0,0,0.05); }
.ts-card.is-highlighted {
  border-color: #409eff;
  box-shadow: 0 0 0 2px rgba(64, 158, 255, 0.15);
}
.ts-card-head {
  display: flex;
  justify-content: space-between;
  align-items: center;
  margin-bottom: 6px;
}
.ts-name {
  display: inline-flex; align-items: center; gap: 6px;
  font-size: 14px; font-weight: 600; color: var(--sk-text);
}
.ts-name .el-icon { color: var(--sk-primary); }
.builtin-pill, .auto-pill {
  font-size: 10px; padding: 1px 6px; border-radius: 3px;
  font-weight: 500;
}
.builtin-pill { background: #ecf5ff; color: var(--sk-primary); }
.auto-pill { background: #fdf6ec; color: #b88230; cursor: help; }
.ts-desc {
  font-size: 12.5px; color: var(--sk-text-muted); line-height: 1.5;
  min-height: 38px; margin-bottom: 10px;
}
.ts-meta { display: flex; gap: 6px; margin-bottom: 10px; }
.meta-chip {
  font-size: 11px; color: var(--sk-text-caption); background: #f5f7fa;
  padding: 2px 8px; border-radius: 10px;
}
.ts-rules-preview {
  font-size: 11.5px;
  color: var(--sk-text-muted);
  font-family: 'SF Mono', Menlo, Consolas, monospace;
  background: #fafbfc;
  border-radius: 4px;
  padding: 8px 10px;
  line-height: 1.6;
}
.rule-gr { font-weight: 600; color: var(--sk-text); }
.rule-arrow { color: var(--sk-text-placeholder); margin: 0 6px; }
.rule-op { color: var(--sk-primary); }
.rule-op code { background: rgba(0,0,0,0.05); padding: 1px 3px; border-radius: 3px; font-size: 10.5px; }
.rule-more { color: var(--sk-text-caption); font-style: italic; margin-top: 4px; }

.more-btn {
  background: none; border: 0;
  color: var(--sk-text-caption); font-size: 18px; cursor: pointer;
  padding: 2px 4px;
}
.more-btn:hover { color: var(--sk-primary); }
.dots { letter-spacing: 1px; }

.loading, .empty {
  text-align: center; padding: 60px 20px; color: var(--sk-text-caption); font-size: 13px;
  background: #fff; border: 1px dashed #dcdfe6; border-radius: 8px;
}
.empty .el-icon { font-size: 28px; display: block; margin: 0 auto 8px; color: var(--sk-text-placeholder); }
.rot { animation: rot 1s linear infinite; }
@keyframes rot { from { transform: rotate(0); } to { transform: rotate(360deg); } }

.editor-body { padding: 0 4px; }
.rules-section { margin-top: 12px; }
.rules-header { display: flex; justify-content: space-between; align-items: center; margin-bottom: 10px; }
.rules-title { font-size: 14px; font-weight: 600; }
.rule-editor {
  border: 1px solid var(--sk-border); border-radius: 6px;
  padding: 12px 14px; margin-bottom: 12px;
  background: #fafbfc;
}
.rule-editor-head { display: flex; justify-content: space-between; align-items: center; margin-bottom: 8px; }
.rule-num { font-size: 12px; color: var(--sk-text-caption); font-weight: 600; }
.patches-section { margin-top: 8px; }
.patches-head {
  display: flex; justify-content: space-between; align-items: center;
  font-size: 12px; color: var(--sk-text-muted); font-weight: 500;
  margin-bottom: 6px;
}
.patch-row {
  display: grid;
  grid-template-columns: 110px 1fr 1fr 32px;
  gap: 6px;
  margin-bottom: 6px;
}
.yaml-preview {
  margin-top: 16px; padding-top: 12px;
  border-top: 1px dashed #ebeef5;
}
.yaml-preview summary {
  font-size: 12px; color: var(--sk-primary); cursor: pointer; user-select: none;
}
.yaml-preview pre {
  margin: 10px 0 0 0;
  background: #1d1e26; color: #e5eaf3;
  padding: 12px 14px; border-radius: 6px;
  font-size: 11.5px; line-height: 1.55;
  font-family: 'SF Mono', Menlo, Consolas, monospace;
  white-space: pre; overflow-x: auto; max-height: 360px;
}

:global(html.dark) .ts-card { background: #1f2026; border-color: #2c2f36; }
:global(html.dark) .ts-card.is-highlighted { border-color: #79bbff; box-shadow: 0 0 0 2px rgba(121,187,255,0.2); }
:global(html.dark) .ts-name { color: #e5eaf3; }
:global(html.dark) .ts-desc { color: #b1b3b8; }
:global(html.dark) .ts-rules-preview { background: #16171b; color: #b1b3b8; }
:global(html.dark) .rule-gr { color: #e5eaf3; }
:global(html.dark) .meta-chip { background: #2c2f36; color: #b1b3b8; }
:global(html.dark) .rule-editor { background: #1a1b21; border-color: #2c2f36; }
:global(html.dark) .loading, :global(html.dark) .empty {
  background: #1f2026; border-color: #3a3d44; color: var(--sk-text-caption);
}
:global(html.dark) .from-conflict-banner { background: #1d3a5f; }
:global(html.dark) .fc-title { color: #e5eaf3; }
</style>
