apiVersion: v2
name: supkube
description: Kubernetes data protection UI powered by Velero
type: application
version: 0.1.1
appVersion: "0.5.1"
keywords:
  - kubernetes
  - velero
  - backup
  - data-protection
