apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "supkube.fullname" . }}-config
  labels:
    {{- include "supkube.labels" . | nindent 4 }}
data:
  veleroNamespace: {{ .Values.config.veleroNamespace | quote }}
  logLevel: {{ .Values.config.logLevel | quote }}
