apiVersion: v1
kind: Service
metadata:
  name: {{ include "supkube.fullname" . }}-backend
  labels:
    {{- include "supkube.labels" . | nindent 4 }}
    app.kubernetes.io/component: backend
spec:
  type: {{ .Values.service.backend.type }}
  ports:
    - port: {{ .Values.service.backend.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "supkube.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: backend
---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "supkube.fullname" . }}-frontend
  labels:
    {{- include "supkube.labels" . | nindent 4 }}
    app.kubernetes.io/component: frontend
spec:
  type: {{ .Values.service.frontend.type }}
  ports:
    - port: {{ .Values.service.frontend.port }}
      targetPort: http
      protocol: TCP
      name: http
      {{- if and (eq .Values.service.frontend.type "NodePort") .Values.service.frontend.nodePort }}
      nodePort: {{ .Values.service.frontend.nodePort }}
      {{- end }}
  selector:
    {{- include "supkube.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: frontend
