// Package v1: artifact_breakdown.go — v0.8.10.1 endpoint that powers the
// Kasten-style Artifacts table in the Action Details drawer.
//
// Why this endpoint exists vs reusing GetBackupArtifacts
// ──────────────────────────────────────────────────────
// `GetBackupArtifacts` (storage.go) was built for the Restore drawer's
// "Spec (N)" preview — it returns FULL YAML per item, focused on a small
// hand-picked GVR set, and is heavy. The Action Details drawer needs the
// opposite: a wide GVR sweep + light item entries (kind + name only) +
// SERVER-SIDE grouping so the UI doesn't have to learn the K8s taxonomy.
//
// Two main design choices:
//
//  1. WIDE GVR sweep. The previous list hit ~8 items for test-app while
//     Velero's progress.totalItems said 38. The gap was sub-resources
//     (Pods/RS/ControllerRevisions), CSI snapshot CRs, Events, etc. —
//     things Velero captures but the old GVR list ignored. We sweep
//     ~30 GVRs here so the breakdown actually reflects what's in the
//     backup tarball.
//
//  2. APPLICATION vs INFRASTRUCTURE classification. Customers ask
//     "what did my app actually back up?". Velero's 38 includes things
//     that aren't strictly "the app": K8s Events generated by CSI
//     snapshot operations, VolumeSnapshot CRs themselves, etc. We split
//     groups into two top-level categories so the drawer can show:
//
//     Application Items: 25  (Workloads, Config, Networking, Storage, RBAC)
//     Infrastructure:    13  (CSI snapshot CRs, Events, auto-generated)
//
//     The "Application Items" number is the v0.8.10.1 #24 stable column —
//     same data path here so the two surfaces stay in sync.
package v1

import (
	"net/http"
	"sort"

	"github.com/gin-gonic/gin"
	velerov1 "github.com/vmware-tanzu/velero/pkg/apis/velero/v1"
	apierrors "k8s.io/apimachinery/pkg/api/errors"
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	"k8s.io/apimachinery/pkg/runtime/schema"
	"sigs.k8s.io/controller-runtime/pkg/client"

	"github.com/supkube/supkube-backend/internal/k8s"
)

// breakdownItem is the per-resource lightweight row. No YAML — the
// drawer only needs name + namespace + kind for the grouped table.
type breakdownItem struct {
	Kind      string `json:"kind"`
	Name      string `json:"name"`
	Namespace string `json:"namespace,omitempty"`
}

// breakdownGroup is one category row in the Artifacts table.
type breakdownGroup struct {
	Key      string          `json:"key"`      // stable id for CSS / i18n key
	Label    string          `json:"label"`    // English fallback display label
	Icon     string          `json:"icon"`     // emoji for the chip
	Category string          `json:"category"` // "application" | "infrastructure"
	Count    int             `json:"count"`
	Items    []breakdownItem `json:"items"`
}

// breakdownResponse is the full payload for the drawer.
type breakdownResponse struct {
	BackupName          string           `json:"backupName"`
	VeleroTotalItems    int              `json:"veleroTotalItems"`    // .status.progress.totalItems verbatim
	ApplicationItems    int              `json:"applicationItems"`    // sum of "application"-category groups
	InfrastructureItems int              `json:"infrastructureItems"` // sum of "infrastructure"-category groups
	Groups              []breakdownGroup `json:"groups"`              // sorted: application categories first, then infra
	// Note + caveat surfacing — frontend uses these to show a "Velero
	// internal count differs because …" footer when veleroTotalItems
	// > applicationItems + infrastructureItems (live-cluster query can
	// miss items that existed at backup time but are gone now).
	Note string `json:"note,omitempty"`
}

// groupDef binds a GVR to a category and display fields. Keeping these
// flat (not nested per-category) makes adding new resource types a
// single-line edit later — the categorization is data, not code.
type groupDef struct {
	gvr      schema.GroupVersionResource
	kind     string
	groupKey string
	cluster  bool // true for cluster-scoped GVRs (we skip per-ns iteration)
}

// breakdownGVRs is the full sweep set. Order doesn't matter — groups
// are aggregated by groupKey afterward. We err on the side of "include
// it" because missing GVRs make the breakdown silently incomplete and
// users blame SupKube rather than the underlying CRD absence.
var breakdownGVRs = []groupDef{
	// ─── Workloads ─────────────────────────────────────────────────
	{schema.GroupVersionResource{Group: "apps", Version: "v1", Resource: "deployments"}, "Deployment", "workloads", false},
	{schema.GroupVersionResource{Group: "apps", Version: "v1", Resource: "statefulsets"}, "StatefulSet", "workloads", false},
	{schema.GroupVersionResource{Group: "apps", Version: "v1", Resource: "daemonsets"}, "DaemonSet", "workloads", false},
	{schema.GroupVersionResource{Group: "apps", Version: "v1", Resource: "replicasets"}, "ReplicaSet", "workloads", false},
	{schema.GroupVersionResource{Group: "apps", Version: "v1", Resource: "controllerrevisions"}, "ControllerRevision", "workloads", false},
	{schema.GroupVersionResource{Group: "", Version: "v1", Resource: "pods"}, "Pod", "workloads", false},
	{schema.GroupVersionResource{Group: "batch", Version: "v1", Resource: "jobs"}, "Job", "workloads", false},
	{schema.GroupVersionResource{Group: "batch", Version: "v1", Resource: "cronjobs"}, "CronJob", "workloads", false},

	// ─── Configuration ─────────────────────────────────────────────
	{schema.GroupVersionResource{Group: "", Version: "v1", Resource: "configmaps"}, "ConfigMap", "config", false},
	{schema.GroupVersionResource{Group: "", Version: "v1", Resource: "secrets"}, "Secret", "config", false},

	// ─── Networking ────────────────────────────────────────────────
	{schema.GroupVersionResource{Group: "", Version: "v1", Resource: "services"}, "Service", "networking", false},
	{schema.GroupVersionResource{Group: "", Version: "v1", Resource: "endpoints"}, "Endpoints", "networking", false},
	{schema.GroupVersionResource{Group: "discovery.k8s.io", Version: "v1", Resource: "endpointslices"}, "EndpointSlice", "networking", false},
	{schema.GroupVersionResource{Group: "networking.k8s.io", Version: "v1", Resource: "ingresses"}, "Ingress", "networking", false},
	{schema.GroupVersionResource{Group: "networking.k8s.io", Version: "v1", Resource: "networkpolicies"}, "NetworkPolicy", "networking", false},

	// ─── Storage ───────────────────────────────────────────────────
	{schema.GroupVersionResource{Group: "", Version: "v1", Resource: "persistentvolumeclaims"}, "PersistentVolumeClaim", "storage", false},

	// ─── RBAC ──────────────────────────────────────────────────────
	{schema.GroupVersionResource{Group: "", Version: "v1", Resource: "serviceaccounts"}, "ServiceAccount", "rbac", false},
	{schema.GroupVersionResource{Group: "rbac.authorization.k8s.io", Version: "v1", Resource: "roles"}, "Role", "rbac", false},
	{schema.GroupVersionResource{Group: "rbac.authorization.k8s.io", Version: "v1", Resource: "rolebindings"}, "RoleBinding", "rbac", false},

	// ─── Autoscaling / Limits (still application) ──────────────────
	{schema.GroupVersionResource{Group: "autoscaling", Version: "v2", Resource: "horizontalpodautoscalers"}, "HorizontalPodAutoscaler", "autoscaling", false},
	{schema.GroupVersionResource{Group: "", Version: "v1", Resource: "resourcequotas"}, "ResourceQuota", "autoscaling", false},
	{schema.GroupVersionResource{Group: "", Version: "v1", Resource: "limitranges"}, "LimitRange", "autoscaling", false},
	{schema.GroupVersionResource{Group: "policy", Version: "v1", Resource: "poddisruptionbudgets"}, "PodDisruptionBudget", "autoscaling", false},

	// ─── Infrastructure: CSI snapshot CRs (created BY snapshot, not part of app) ──
	{schema.GroupVersionResource{Group: "snapshot.storage.k8s.io", Version: "v1", Resource: "volumesnapshots"}, "VolumeSnapshot", "snapshotCRs", false},

	// ─── Infrastructure: K8s Events generated by recent snapshot/upload activity ──
	// Events are large in count + low signal for "what's in my app".
	// Velero v1.18 captures them per-namespace when they're recent enough.
	{schema.GroupVersionResource{Group: "", Version: "v1", Resource: "events"}, "Event", "events", false},
	{schema.GroupVersionResource{Group: "events.k8s.io", Version: "v1", Resource: "events"}, "Event", "events", false},
}

// groupMeta supplies display info for each groupKey. Kept separate from
// the GVR list so we don't repeat icon/label across multiple GVR rows
// that fall into the same group (e.g. all five workload GVRs share one
// "Workloads" header).
var groupMeta = map[string]struct {
	Label    string
	Icon     string
	Category string
	Order    int
}{
	"workloads":   {"Workloads", "📦", "application", 1},
	"config":      {"Configuration", "⚙️", "application", 2},
	"networking":  {"Networking", "🌐", "application", 3},
	"storage":     {"Storage", "💾", "application", 4},
	"rbac":        {"RBAC", "🔑", "application", 5},
	"autoscaling": {"Autoscaling & Limits", "📈", "application", 6},
	"snapshotCRs": {"CSI Snapshot CRs", "📸", "infrastructure", 10},
	"events":      {"Kubernetes Events", "📨", "infrastructure", 11},
	"other":       {"Other", "📁", "infrastructure", 12},
}

// excludeFromBreakdown is the same denylist GetBackupArtifacts uses,
// extracted into a helper so both endpoints stay in sync.
func excludeFromBreakdown(resource, name string) bool {
	if resource == "configmaps" && name == "kube-root-ca.crt" {
		return true
	}
	return false
}

// GetBackupArtifactBreakdown returns the grouped artifact view for one
// Backup. Powers the Action Details drawer's Artifacts table (v0.8.10.1
// task #23) and the Restore Points "Application Items" column (#24).
//
// Strategy: same live-cluster sweep as ListBackupArtifacts, with a much
// wider GVR set, lightweight items (no YAML), and server-side grouping.
// When the source namespace is gone (backup older than the app's
// lifetime), we fall back to reporting Velero's totalItems with a note
// explaining the breakdown is unavailable.
func GetBackupArtifactBreakdown(c *gin.Context) {
	name := c.Param("name")
	rcl, err := k8s.GetRuntimeClient()
	if err != nil {
		c.JSON(http.StatusInternalServerError, gin.H{"error": err.Error()})
		return
	}
	backup := &velerov1.Backup{}
	if err := rcl.Get(c.Request.Context(), client.ObjectKey{Name: name, Namespace: "velero"}, backup); err != nil {
		c.JSON(http.StatusNotFound, gin.H{"error": err.Error()})
		return
	}

	resp := breakdownResponse{BackupName: name}
	if backup.Status.Progress != nil {
		resp.VeleroTotalItems = int(backup.Status.Progress.TotalItems)
	}

	namespaces := backup.Spec.IncludedNamespaces
	if len(namespaces) == 0 {
		resp.Note = "Whole-cluster backup or no included namespaces — breakdown unavailable for this v0.8.10.1 endpoint."
		c.JSON(http.StatusOK, resp)
		return
	}

	dcl, err := k8s.GetDynamicClient()
	if err != nil {
		c.JSON(http.StatusInternalServerError, gin.H{"error": err.Error()})
		return
	}

	// Apply the same labelSelector the Backup used so we don't oversell
	// (a label-selected backup would otherwise look like it backed up
	// the whole ns).
	listOpts := metav1.ListOptions{}
	if backup.Spec.LabelSelector != nil {
		listOpts.LabelSelector = metav1.FormatLabelSelector(backup.Spec.LabelSelector)
	}

	// groupBuckets indexes items by groupKey for aggregation.
	groupBuckets := map[string][]breakdownItem{}

	for _, ns := range namespaces {
		for _, gd := range breakdownGVRs {
			list, err := dcl.Resource(gd.gvr).Namespace(ns).List(c.Request.Context(), listOpts)
			if err != nil {
				// CRD absent (e.g. snapshot.storage.k8s.io on clusters
				// without CSI) or RBAC missing → skip silently. We don't
				// want one missing GVR to break the whole breakdown.
				if apierrors.IsNotFound(err) || apierrors.IsForbidden(err) {
					continue
				}
				continue
			}
			for _, obj := range list.Items {
				itemName := obj.GetName()
				if excludeFromBreakdown(gd.gvr.Resource, itemName) {
					continue
				}
				// Same Secret denylist as ListBackupArtifacts: skip
				// Helm release storage + SA tokens (auto-managed,
				// noise in the drawer).
				if gd.gvr.Resource == "secrets" {
					t, _, _ := unstructuredString(obj.Object, "type")
					if t == "helm.sh/release.v1" || t == "kubernetes.io/service-account-token" {
						continue
					}
				}
				groupBuckets[gd.groupKey] = append(groupBuckets[gd.groupKey], breakdownItem{
					Kind:      gd.kind,
					Name:      itemName,
					Namespace: ns,
				})
			}
		}
	}

	// Materialize groups in stable order (application first by
	// groupMeta.Order, then infrastructure). Empty groups omitted.
	for key, items := range groupBuckets {
		meta, ok := groupMeta[key]
		if !ok {
			meta = groupMeta["other"]
		}
		// Stable secondary sort within each group: by Kind then Name.
		sort.Slice(items, func(i, j int) bool {
			if items[i].Kind != items[j].Kind {
				return items[i].Kind < items[j].Kind
			}
			return items[i].Name < items[j].Name
		})
		group := breakdownGroup{
			Key:      key,
			Label:    meta.Label,
			Icon:     meta.Icon,
			Category: meta.Category,
			Count:    len(items),
			Items:    items,
		}
		if group.Category == "application" {
			resp.ApplicationItems += group.Count
		} else {
			resp.InfrastructureItems += group.Count
		}
		resp.Groups = append(resp.Groups, group)
	}
	sort.SliceStable(resp.Groups, func(i, j int) bool {
		oi := groupMeta[resp.Groups[i].Key].Order
		oj := groupMeta[resp.Groups[j].Key].Order
		return oi < oj
	})

	// Surface the gap between Velero's count and our live-cluster sweep.
	// Common causes the note is meant to head off:
	//   - Source ns deleted after backup → live query returns 0 even
	//     though Velero captured items at backup time
	//   - Velero captured cluster-scoped sub-resources (PV, etc.) that
	//     we don't query namespace-by-namespace
	//   - Auto-generated items expired between backup time and now
	//     (Events have ~1h TTL)
	totalCounted := resp.ApplicationItems + resp.InfrastructureItems
	if resp.VeleroTotalItems > 0 && totalCounted < resp.VeleroTotalItems {
		gap := resp.VeleroTotalItems - totalCounted
		resp.Note = "Live-cluster query found " + intToStr(totalCounted) +
			" items; Velero's recorded total is " + intToStr(resp.VeleroTotalItems) +
			" (" + intToStr(gap) + " items not visible — likely auto-expired Events " +
			"or resources from cluster-scoped sweeps). Application Items count is stable across runs."
	}
	c.JSON(http.StatusOK, resp)
}

// intToStr is a tiny helper to avoid pulling strconv just for the Note
// string. strconv would work fine; this is just less import noise.
func intToStr(i int) string {
	if i == 0 {
		return "0"
	}
	neg := i < 0
	if neg {
		i = -i
	}
	var buf [20]byte
	pos := len(buf)
	for i > 0 {
		pos--
		buf[pos] = byte('0' + i%10)
		i /= 10
	}
	if neg {
		pos--
		buf[pos] = '-'
	}
	return string(buf[pos:])
}
