// Package v1: backup composition metadata (v0.8.6).
//
// This file builds the SupKube-specific enrichment that hangs off every
// Backup CR we return — answers the user's three v0.8.5-aftermath
// questions:
//
//   1. "Is this full or incremental?"  → DataPath chip
//   2. "How big is this backup?"        → SizeBytes (resource tarball) +
//                                          VolumeBytes (declared PV capacity)
//   3. "What's the compression ratio?"  → (deferred to v0.9; needs Kopia
//                                          integration — see ADR-021)
//
// We do NOT mutate the upstream velerov1.Backup struct. Instead we wrap:
//
//   {
//     "metadata": { ... },          ← velerov1.Backup as-is
//     "spec":     { ... },
//     "status":   { ... },
//     "supkube": {                  ← our enrichment
//       "dataPath":      "csi-snapshot",
//       "volumeCount":   2,
//       "volumeBytes":   6442450944,
//       "tarballBytes":  18432
//     }
//   }
//
// The wrap keeps every existing frontend `row.metadata.name` reference
// working, and isolates our additions under a single `supkube` key —
// future v0.9 fields (compressionRatio, dedupRatio, etc.) slot in
// without breaking the Velero-shaped contract.
package v1

import (
	"context"

	snapshotv1 "github.com/kubernetes-csi/external-snapshotter/client/v8/apis/volumesnapshot/v1"
	velerov1 "github.com/vmware-tanzu/velero/pkg/apis/velero/v1"
	velerov2alpha1 "github.com/vmware-tanzu/velero/pkg/apis/velero/v2alpha1"
	corev1 "k8s.io/api/core/v1"
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	"k8s.io/apimachinery/pkg/runtime/schema"
	"sigs.k8s.io/controller-runtime/pkg/client"

	"github.com/supkube/supkube-backend/internal/k8s"
)

// SupKubeBackupMeta is the "supkube" sidecar attached to each enriched
// Backup response. All fields are best-effort — missing data renders as
// zero/empty, never blocks the row from showing.
type SupKubeBackupMeta struct {
	// DataPath classifies HOW the volume data was protected. See
	// classifyDataPath() for the full enum.
	DataPath string `json:"dataPath"`

	// VolumeCount = number of PVs included in this backup. Pulled from
	// status.csiVolumeSnapshotsCompleted for the CSI path; from
	// PodVolumeBackups for the FS path; 0 for metadata-only.
	VolumeCount int `json:"volumeCount"`

	// VolumeBytes = "actual" bytes processed.
	//   - data-mover / filesystem: DataUpload / PodVolumeBackup
	//     progress.totalBytes — the size Velero/Kopia actually moved
	//   - csi-snapshot: VolumeSnapshotContent.status.restoreSize when
	//     the VSC is still present; 0 when Velero v1.18 has deleted it
	VolumeBytes int64 `json:"volumeBytes"`

	// ReservedBytes (v0.8.10.4) = sum of source PVC `.spec.resources
	// .requests.storage` for the namespaces in this Backup. Always
	// available regardless of dataPath — populated by querying the live
	// PVC list at response time. Renders as the denominator in the UI's
	// "actual / reserved" Size cell, so Snapshot RPs (whose VSC may
	// have been auto-deleted by Velero v1.18) still show a meaningful
	// number. Falls back to 0 only when the source namespace no longer
	// exists in the cluster.
	ReservedBytes int64 `json:"reservedBytes,omitempty"`

	// ApplicationItems (v0.8.11) = number of "real application" K8s
	// resources in the backup's source namespaces, excluding the noise
	// that Velero's raw progress.totalItems contains (Kubernetes Events
	// generated by the snapshot operation + snapshot.storage.k8s.io
	// CRs themselves + Helm-internal secrets + auto-generated SA
	// tokens). Stable across runs: doesn't change just because the
	// previous snapshot wrote a Snapshotting/Snapshotted Event.
	//
	// Computed via the same GVR sweep as artifact-breakdown but limited
	// to the "application" category groups. Live-cluster query — if the
	// source ns is gone (rare; deleted after backup), returns 0.
	ApplicationItems int `json:"applicationItems,omitempty"`

	// TarballBytes = size of the K8s resource manifest tarball on BSL.
	// Tens of KB usually — useful for showing "we DO have the resources
	// catalogued" but small enough that displaying it next to volume
	// bytes is just informational, not a primary KPI.
	TarballBytes int64 `json:"tarballBytes,omitempty"`

	// TarballError surfaces a 1-line reason when we couldn't read the
	// BSL (creds missing, bucket unavailable, etc.) so the user sees
	// "tarball size unavailable: BSL Unavailable" instead of silent zero.
	TarballError string `json:"tarballError,omitempty"`
}

// Data path enum values. Returned in SupKubeBackupMeta.DataPath. The
// frontend renders these as color-coded chips with tooltips.
const (
	DataPathCSISnapshot  = "csi-snapshot"  // CSI snapshot, stays on cluster (CoW)
	DataPathDataMover    = "data-mover"    // CSI snapshot moved to object store via Kopia
	DataPathFilesystem   = "filesystem"    // Restic/Kopia walking the filesystem
	DataPathMetadataOnly = "metadata-only" // K8s YAML only, no volume data
	DataPathUnknown      = "unknown"       // shouldn't happen; defensive
)

// classifyDataPath inspects a Backup's spec + status to figure out which
// data path it used. We look at status fields (not just spec) so that
// per-volume opt-out via PVC annotations is reflected when possible —
// e.g. a backup that declares CSI but had 0 CSI snapshots taken is
// effectively metadata-only.
//
// Decision tree (first match wins):
//
//   spec.snapshotMoveData == true              → data-mover
//   spec.defaultVolumesToFsBackup == true      → filesystem
//   spec.snapshotVolumes == true && csiCount>0 → csi-snapshot
//   spec.snapshotVolumes == true && csiCount=0 → metadata-only (declared CSI but nothing snapshotted)
//   else                                       → metadata-only
//
// Why we trust status over spec: a backup may declare CSI but if all
// included PVs were on storage classes without snapshot support, no
// snapshots actually get created and the user effectively has a
// metadata-only restore point. Showing "csi-snapshot" in that case
// would be misleading.
func classifyDataPath(b *velerov1.Backup) string {
	if b == nil {
		return DataPathUnknown
	}
	spec := b.Spec
	status := b.Status

	// Data Mover takes priority — it's a layered mode on top of CSI,
	// and once moved the data is no longer cluster-local.
	if spec.SnapshotMoveData != nil && *spec.SnapshotMoveData {
		return DataPathDataMover
	}

	// Filesystem backup is an explicit opt-in, not the default.
	if spec.DefaultVolumesToFsBackup != nil && *spec.DefaultVolumesToFsBackup {
		return DataPathFilesystem
	}

	// CSI snapshots — but only if they actually happened.
	wantCSI := spec.SnapshotVolumes == nil || *spec.SnapshotVolumes
	if wantCSI && status.CSIVolumeSnapshotsCompleted > 0 {
		return DataPathCSISnapshot
	}

	// Declared CSI but nothing snapshotted (no-storage workload, or
	// snapshot class missing) → effectively metadata-only.
	return DataPathMetadataOnly
}

// collectVolumeMetadata pulls per-backup volume counts + sizes from the
// cluster. We DO NOT call this for every backup in a list (would be
// O(N) round-trips); ListBackups instead does ONE upfront query for
// each CR type and joins by label.
//
// This function is for the per-backup detail view where N=1.
//
// Three CR types feed the totals because a backup can take three paths:
//
//   CSI snapshot only  → VolumeSnapshotContent  status.restoreSize
//   Filesystem backup  → PodVolumeBackup        status.progress.totalBytes
//   Data Mover         → DataUpload             status.progress.totalBytes
//
// A backup uses exactly one path (we reject "both" in CreateBackup), so
// the sums don't double-count. Mixing PVB + DU for example is impossible
// by the validation in CreateBackup / collapseToVelero.
func collectVolumeMetadata(ctx context.Context, cl client.Client, backupName string) (volumeCount int, volumeBytes int64) {
	// CSI path: VolumeSnapshotContents are cluster-scoped and labeled
	// with velero.io/backup-name. status.restoreSize gives declared
	// capacity (bytes, int64) — see ADR-021 for why this isn't the
	// "actual data" metric users intuitively expect.
	vscList := &snapshotv1.VolumeSnapshotContentList{}
	if err := cl.List(ctx, vscList, client.MatchingLabels{"velero.io/backup-name": backupName}); err == nil {
		for _, vsc := range vscList.Items {
			if vsc.Status != nil && vsc.Status.RestoreSize != nil {
				volumeBytes += *vsc.Status.RestoreSize
				volumeCount++
			}
		}
	}

	// Filesystem path: PodVolumeBackups carry actual bytes processed.
	// Velero labels them with velero.io/backup-name too. Aggregate
	// alongside CSI — a backup may legitimately have both (PVs on
	// CSI-compatible storage class are snapshotted; others fall back
	// to fs backup).
	pvbList := &velerov1.PodVolumeBackupList{}
	if err := cl.List(ctx, pvbList, client.InNamespace("velero"), client.MatchingLabels{"velero.io/backup-name": backupName}); err == nil {
		for _, pvb := range pvbList.Items {
			// PodVolumeBackup.Status.Progress has TotalBytes — bytes
			// actually written, which is what we WANT here. Falls
			// back to 0 when the backup hasn't completed.
			volumeBytes += pvb.Status.Progress.TotalBytes
			volumeCount++
		}
	}

	// Data Mover path (v0.8.7.3): DataUpload CR in velero.io/v2alpha1.
	// Same labeling convention. Status.Progress.TotalBytes is the
	// post-Kopia logical bytes (raw source size; physical-on-storage
	// is smaller because Kopia dedupes + compresses).
	//
	// Empty PVCs (zero data) produce DataUploads with TotalBytes=0;
	// we still count them in volumeCount because the volume WAS
	// processed — showing "0 bytes, 2 volumes" tells the user
	// "you protected 2 volumes; one happened to be empty".
	duList := &velerov2alpha1.DataUploadList{}
	if err := cl.List(ctx, duList, client.InNamespace("velero"), client.MatchingLabels{"velero.io/backup-name": backupName}); err == nil {
		for _, du := range duList.Items {
			volumeBytes += du.Status.Progress.TotalBytes
			volumeCount++
		}
	}

	return volumeCount, volumeBytes
}

// reservedBytesForBackup returns the sum of `.spec.resources.requests
// .storage` across all PVCs in the backup's source namespaces. Always
// resolves via the live K8s API — does NOT depend on the backup's
// VolumeSnapshotContent CRs being intact (those get auto-deleted by
// Velero v1.18 for snapshotMoveData=true paths, leaving VolumeBytes=0).
//
// Returns 0 silently when:
//   - backup has no includedNamespaces (whole-cluster backup; we can't
//     reasonably scope "this app's reserved capacity")
//   - PVC listing failed for any reason (perms, ns gone, etc.)
//
// Cheap: 1 PVC list per included namespace. Aggregated across all
// backups via reservedBytesBatch below for list responses.
func reservedBytesForBackup(ctx context.Context, cl client.Client, b *velerov1.Backup) int64 {
	if len(b.Spec.IncludedNamespaces) == 0 {
		return 0
	}
	var total int64
	for _, ns := range b.Spec.IncludedNamespaces {
		pvcList := &corev1.PersistentVolumeClaimList{}
		if err := cl.List(ctx, pvcList, client.InNamespace(ns)); err != nil {
			continue // best-effort
		}
		for i := range pvcList.Items {
			req := pvcList.Items[i].Spec.Resources.Requests
			if q, ok := req[corev1.ResourceStorage]; ok {
				if v, ok := q.AsInt64(); ok {
					total += v
				}
			}
		}
	}
	return total
}

// reservedBytesBatch precomputes reserved-bytes for a backup list with
// a single PVC list call per unique included namespace — turns N×M
// queries into N+M for a list of N backups across M namespaces.
func reservedBytesBatch(ctx context.Context, cl client.Client, backups []velerov1.Backup) map[string]int64 {
	// 1. gather unique namespaces
	nsSet := map[string]struct{}{}
	for i := range backups {
		for _, ns := range backups[i].Spec.IncludedNamespaces {
			nsSet[ns] = struct{}{}
		}
	}
	// 2. one PVC list per ns, then sum per ns
	byNs := map[string]int64{}
	for ns := range nsSet {
		pvcList := &corev1.PersistentVolumeClaimList{}
		if err := cl.List(ctx, pvcList, client.InNamespace(ns)); err != nil {
			continue
		}
		var sum int64
		for i := range pvcList.Items {
			req := pvcList.Items[i].Spec.Resources.Requests
			if q, ok := req[corev1.ResourceStorage]; ok {
				if v, ok := q.AsInt64(); ok {
					sum += v
				}
			}
		}
		byNs[ns] = sum
	}
	// 3. attribute to each backup by summing its includedNamespaces
	out := map[string]int64{}
	for i := range backups {
		b := &backups[i]
		var total int64
		for _, ns := range b.Spec.IncludedNamespaces {
			total += byNs[ns]
		}
		out[b.Name] = total
	}
	return out
}

// applicationItemsBatch computes per-backup application-item counts for
// a list response. Same categorisation as the artifact-breakdown
// endpoint, but limited to the "application" group set so the column
// shows a stable per-app number that's not inflated by:
//
//   - Kubernetes Events generated by recent snapshot activity
//   - snapshot.storage.k8s.io CRs (VS / VSC / VSClass)
//   - Helm release-storage secrets / auto-generated SA tokens
//
// Batched: one PVC/Pod/etc list per UNIQUE namespace, not per backup.
// For a typical 15-row Restore Points page with 2-3 ns spanned,
// ~22 GVR queries × ~3 ns = ~66 list calls — bounded, parallelisable
// (we don't, current latency is fine), and idempotent.
//
// Returns map[backupName]int. Lookup miss = 0, never errors out the
// whole request — the column degrades to "0" rather than blanking
// the whole page.
func applicationItemsBatch(ctx context.Context, backups []velerov1.Backup) map[string]int {
	// 1. Distinct ns set across all backups
	nsSet := map[string]struct{}{}
	for i := range backups {
		for _, ns := range backups[i].Spec.IncludedNamespaces {
			nsSet[ns] = struct{}{}
		}
	}
	if len(nsSet) == 0 {
		return map[string]int{}
	}

	dcl, err := k8s.GetDynamicClient()
	if err != nil {
		return map[string]int{}
	}

	// 2. Build the filtered "application only" GVR list. We reuse the
	//    same breakdownGVRs set + groupMeta from artifact_breakdown.go
	//    so the column count and the drawer's grouped table stay in
	//    sync — change one, the other updates.
	type gvrEntry struct {
		gvr      schema.GroupVersionResource
		resource string
	}
	appGVRs := make([]gvrEntry, 0, len(breakdownGVRs))
	for _, gd := range breakdownGVRs {
		meta, ok := groupMeta[gd.groupKey]
		if !ok || meta.Category != "application" {
			continue
		}
		appGVRs = append(appGVRs, gvrEntry{gvr: gd.gvr, resource: gd.gvr.Resource})
	}

	// 3. For each ns, count application items.
	countsByNs := map[string]int{}
	for ns := range nsSet {
		var total int
		for _, e := range appGVRs {
			list, err := dcl.Resource(e.gvr).Namespace(ns).List(ctx, metav1.ListOptions{})
			if err != nil {
				continue
			}
			for i := range list.Items {
				name := list.Items[i].GetName()
				if excludeFromBreakdown(e.resource, name) {
					continue
				}
				// Mirror the Secret filter from artifact-breakdown so the
				// number doesn't include Helm release storage / SA tokens.
				if e.resource == "secrets" {
					t, _, _ := unstructuredString(list.Items[i].Object, "type")
					if t == "helm.sh/release.v1" || t == "kubernetes.io/service-account-token" {
						continue
					}
				}
				total++
			}
		}
		countsByNs[ns] = total
	}

	// 4. Attribute to each backup by summing its includedNamespaces.
	out := map[string]int{}
	for i := range backups {
		b := &backups[i]
		var total int
		for _, ns := range b.Spec.IncludedNamespaces {
			total += countsByNs[ns]
		}
		out[b.Name] = total
	}
	return out
}

// collectVolumeMetadataBatch is the list-friendly version: one cluster
// query per CR type, then in-memory join. Used by ListBackups so a
// 100-row page stays at O(3) API calls instead of O(100*3).
//
// v0.8.7.3: extended to also list DataUploads. A Data Mover backup's
// volumeBytes / volumeCount came back as 0 before this — we were only
// counting VSC and PVB, missing the third path entirely. Discovered
// during the first real end-to-end Azure DR test (32 MB postgres
// data shipped to Blob but UI said "0 bytes").
//
// Returns a map keyed by backup name → (count, bytes).
func collectVolumeMetadataBatch(ctx context.Context, cl client.Client) map[string]struct{ Count int; Bytes int64 } {
	result := map[string]struct{ Count int; Bytes int64 }{}
	add := func(name string, bytes int64) {
		v := result[name]
		v.Count++
		v.Bytes += bytes
		result[name] = v
	}

	// CSI snapshot — cluster-scoped CR; one List for the whole cluster.
	vscList := &snapshotv1.VolumeSnapshotContentList{}
	if err := cl.List(ctx, vscList); err == nil {
		for _, vsc := range vscList.Items {
			name, ok := vsc.Labels["velero.io/backup-name"]
			if !ok || name == "" {
				continue
			}
			if vsc.Status != nil && vsc.Status.RestoreSize != nil {
				add(name, *vsc.Status.RestoreSize)
			}
		}
	}

	// Filesystem backup — namespaced; one List in velero ns.
	pvbList := &velerov1.PodVolumeBackupList{}
	if err := cl.List(ctx, pvbList, client.InNamespace("velero")); err == nil {
		for _, pvb := range pvbList.Items {
			name, ok := pvb.Labels["velero.io/backup-name"]
			if !ok || name == "" {
				continue
			}
			add(name, pvb.Status.Progress.TotalBytes)
		}
	}

	// Data Mover (v2alpha1) — namespaced; one List in velero ns.
	duList := &velerov2alpha1.DataUploadList{}
	if err := cl.List(ctx, duList, client.InNamespace("velero")); err == nil {
		for _, du := range duList.Items {
			name, ok := du.Labels["velero.io/backup-name"]
			if !ok || name == "" {
				continue
			}
			add(name, du.Status.Progress.TotalBytes)
		}
	}

	return result
}
