import { createRouter, createWebHistory } from 'vue-router'
import Dashboard from '../views/Dashboard.vue'
import { useAuth } from '../composables/useAuth'
// PRD-028: router base derives from the runtime basePath ('/' by default).
import { basePath } from '../basePath'

const routes = [
  // v0.8.5: Login route — public, no guard.
  { path: '/login', name: 'Login', component: () => import('../views/Login.vue'), meta: { public: true } },
  // Same component handles the OIDC callback (Dex redirects here with ?code).
  { path: '/auth/callback', name: 'AuthCallback', component: () => import('../views/Login.vue'), meta: { public: true } },

  { path: '/', redirect: '/dashboard' },
  { path: '/dashboard', name: 'Dashboard', component: Dashboard },
  // PRD-011 §4.6: DR Health Score Dashboard — per-app backup posture scoring
  // + actionable advice, fed by GET /ai/scores (collector + evaluator).
  // v0.9.1.x: folded into the Observability hub as its first tab (DRScores.vue
  // is now a tab pane). Old /dr-scores bookmarks redirect to the tab.
  { path: '/dr-scores', redirect: '/observability?tab=dr' },
  // v0.9.0.2: MCM Dashboard — the page Mode Switcher → "Multi-Cluster
  // Manager" lands on. Aggregated view across all registered clusters.
  { path: '/multicluster', name: 'Multicluster', component: () => import('../views/MulticlusterDashboard.vue') },
  { path: '/applications', name: 'Applications', component: () => import('../views/Applications.vue') },
  { path: '/backups', name: 'Backups', component: () => import('../views/Backups.vue') },
  { path: '/backups/:name', name: 'BackupDetail', component: () => import('../views/BackupDetail.vue') },
  // v0.8.0: Activity replaces the Restores page. Keep /restores as a
  // redirect for any bookmarks/external links that still point at it.
  // v0.9.1.2: Activity + Advisor + Audit Log + (future) Log Viewer folded
  // into "Observability" hub. The standalone routes stay valid for deep
  // links / admin shortcuts; only the sidebar entries were retired.
  { path: '/observability', name: 'Observability', component: () => import('../views/Observability.vue') },
  { path: '/activity', name: 'Activity', component: () => import('../views/Activity.vue') },
  { path: '/restores', redirect: '/observability?tab=activity' },
  { path: '/policies', name: 'Policies', component: () => import('../views/Policies.vue') },
  { path: '/transform-sets', name: 'TransformSets', component: () => import('../views/TransformSets.vue') },
  // PRD-002 v1.3 (2026-05-31) two-layer Transform model — atomic Transform
  // editor. RestoreDrawer "Go to Transform" CTA navigates here with
  // `?fromConflict=&payload=` (fresh editor) or `?name=<auto-generated>`
  // (review the Transform produced by Pre-flight Apply Fix). Replaces the
  // v0.9.x placeholder that redirected to /transform-sets.
  { path: '/transforms', name: 'Transforms', component: () => import('../views/Transforms.vue') },
  { path: '/storage', name: 'StorageLocations', component: () => import('../views/StorageLocations.vue') },
  { path: '/snapshot-locations', name: 'VolumeSnapshotLocations', component: () => import('../views/VolumeSnapshotLocations.vue') },
  { path: '/advisor', name: 'BackupAdvisor', component: () => import('../views/BackupAdvisor.vue') },
  { path: '/settings', name: 'Settings', component: () => import('../views/Settings.vue') },
]

const router = createRouter({
  history: createWebHistory(basePath),
  routes
})

// v0.8.5 navigation guard. We need useAuth() to be initialized before we
// can read isLoggedIn — so we bootstrap once and then gate every
// subsequent navigation. Public routes (login, callback) always pass.
let authBootstrapped = false
router.beforeEach(async (to) => {
  if (to.meta?.public) return true

  const auth = useAuth()
  if (!authBootstrapped) {
    await auth.bootstrap()
    authBootstrapped = true
  }
  if (auth.isLoggedIn.value) return true
  // Not logged in → bounce to /login. Preserve where they were trying
  // to go so we can return them there after login (future v0.8.6).
  return { path: '/login', query: { redirect: to.fullPath } }
})

export default router
